version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoUser
      - MONGO_INITDB_ROOT_PASSWORD=mongoPassword
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  api:
    build: .
    container_name: api
    restart: always
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongoUser:mongoPassword@mongodb:27017/recipeDB
      - NODE_ENV=production
      - PORT=5000
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    working_dir: /app
    command: ["pm2-runtime", "index.js"]

volumes:
  mongo-data:
    driver: local
